import { FeatureDefinition } from "@/types/featureControl";

export const FEATURE_REGISTRY: FeatureDefinition[] = [
  // =========================================================================
  // 1. MODULES (9 CORE MODULES)
  // =========================================================================
  {
    id: "module:students",
    key: "students",
    name: "Students Management",
    moduleKey: "students",
    category: "module",
    description: "Complete student directory, admissions, roster, and profile records.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students", method: "ALL" }],
  },
  {
    id: "module:teachers",
    key: "teachers",
    name: "Teachers & Faculty",
    moduleKey: "teachers",
    category: "module",
    description: "Faculty management, subject allocations, and teacher onboarding.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/teachers", method: "ALL" }],
  },
  {
    id: "module:attendance",
    key: "attendance",
    name: "Attendance Management",
    moduleKey: "attendance",
    category: "module",
    description: "Daily and period-wise student & teacher attendance tracking.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/attendance", method: "ALL" }],
  },
  {
    id: "module:fees",
    key: "fees",
    name: "Fee Management & Accounting",
    moduleKey: "fees",
    category: "module",
    description: "Fee structures, offline & online payment collection, receipts, and ledger.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees", method: "ALL" }],
  },
  {
    id: "module:homework",
    key: "homework",
    name: "Homework & Assignments",
    moduleKey: "homework",
    category: "module",
    description: "Assignment publishing, student homework submissions, and evaluations.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/homework", method: "ALL" }],
  },
  {
    id: "module:reports",
    key: "reports",
    name: "Reports & Analytics",
    moduleKey: "reports",
    category: "module",
    description: "Academic reports, fee summaries, attendance analytics, and data exports.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/reports", method: "ALL" }],
  },
  {
    id: "module:exams",
    key: "exams",
    name: "Examinations & Marks",
    moduleKey: "exams",
    category: "module",
    description: "Exam schedules, grade books, report cards, and mark sheets.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/exams", method: "ALL" }],
  },
  {
    id: "module:notices",
    key: "notices",
    name: "Notices & Announcements",
    moduleKey: "notices",
    category: "module",
    description: "Broadcast circulars, notices to parents, teachers, and school-wide alerts.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/notices", method: "ALL" }],
  },
  {
    id: "module:timetable",
    key: "timetable",
    name: "Class Timetable",
    moduleKey: "timetable",
    category: "module",
    description: "Class schedule planning, period allocations, and teacher timetables.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/timetable", method: "ALL" }],
  },

  // =========================================================================
  // 2. GRANULAR FEATURES
  // =========================================================================
  // Module: Students
  {
    id: "feature:students.view",
    key: "students.view",
    name: "View Students Directory",
    moduleKey: "students",
    category: "feature",
    description: "Browse student rosters, classes, and search student profiles.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students", method: "GET" }],
  },
  {
    id: "feature:students.create",
    key: "students.create",
    name: "Enroll New Student",
    moduleKey: "students",
    category: "feature",
    description: "Add individual student accounts and assign to class/section.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students", method: "POST" }],
  },
  {
    id: "feature:students.edit",
    key: "students.edit",
    name: "Edit Student Profile",
    moduleKey: "students",
    category: "feature",
    description: "Modify student bio, parent contacts, roll number, and status.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students", method: "PATCH" }],
  },
  {
    id: "feature:students.delete",
    key: "students.delete",
    name: "Delete / Remove Student",
    moduleKey: "students",
    category: "feature",
    description: "Permanently delete student record or archive credentials.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students", method: "DELETE" }],
  },
  {
    id: "feature:students.import",
    key: "students.import",
    name: "Bulk Import Students (CSV/Excel)",
    moduleKey: "students",
    category: "feature",
    description: "Upload bulk student spreadsheets to provision hundreds of students.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students/import", method: "POST" }],
  },
  {
    id: "feature:students.export",
    key: "students.export",
    name: "Export Student Roster",
    moduleKey: "students",
    category: "feature",
    description: "Download student roster lists as CSV or Excel.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students/export", method: "GET" }],
  },

  // Module: Teachers
  {
    id: "feature:teachers.view",
    key: "teachers.view",
    name: "View Faculty Directory",
    moduleKey: "teachers",
    category: "feature",
    description: "Browse teachers, qualifications, and assigned classes.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/teachers", method: "GET" }],
  },
  {
    id: "feature:teachers.create",
    key: "teachers.create",
    name: "Add Faculty Member",
    moduleKey: "teachers",
    category: "feature",
    description: "Onboard teacher and generate login credentials.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/teachers", method: "POST" }],
  },
  {
    id: "feature:teachers.edit",
    key: "teachers.edit",
    name: "Edit Faculty Details",
    moduleKey: "teachers",
    category: "feature",
    description: "Update teacher information and subjects.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/teachers", method: "PATCH" }],
  },
  {
    id: "feature:teachers.delete",
    key: "teachers.delete",
    name: "Deactivate / Delete Teacher",
    moduleKey: "teachers",
    category: "feature",
    description: "Revoke teacher portal access and remove account.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/teachers", method: "DELETE" }],
  },
  {
    id: "feature:teachers.assign",
    key: "teachers.assign",
    name: "Assign Class & Subjects",
    moduleKey: "teachers",
    category: "feature",
    description: "Designate class teachers and subject master assignments.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/teachers/assign", method: "POST" }],
  },

  // Module: Attendance
  {
    id: "feature:attendance.view",
    key: "attendance.view",
    name: "View Daily Attendance",
    moduleKey: "attendance",
    category: "feature",
    description: "Inspect daily class attendance rolls and student attendance records.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/attendance", method: "GET" }],
  },
  {
    id: "feature:attendance.mark",
    key: "attendance.mark",
    name: "Mark Attendance",
    moduleKey: "attendance",
    category: "feature",
    description: "Record daily present/absent/late attendance for classes.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/attendance", method: "POST" }],
  },
  {
    id: "feature:attendance.edit",
    key: "attendance.edit",
    name: "Edit Historical Attendance",
    moduleKey: "attendance",
    category: "feature",
    description: "Retroactively adjust past attendance records and leave justifications.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/attendance", method: "PATCH" }],
  },
  {
    id: "feature:attendance.export",
    key: "attendance.export",
    name: "Export Attendance Registers",
    moduleKey: "attendance",
    category: "feature",
    description: "Download monthly and annual attendance registers.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/attendance/export", method: "GET" }],
  },

  // Module: Fees
  {
    id: "feature:fees.view",
    key: "fees.view",
    name: "View Fee Dashboard & Records",
    moduleKey: "fees",
    category: "feature",
    description: "Inspect collection statistics, pending fee defaulters, and invoices.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees", method: "GET" }],
  },
  {
    id: "feature:fees.collect",
    key: "fees.collect",
    name: "Collect Fee Payment",
    moduleKey: "fees",
    category: "feature",
    description: "Accept and record offline fee collections and print receipts.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees/collect", method: "POST" }],
  },
  {
    id: "feature:fees.adjust",
    key: "fees.adjust",
    name: "Fee Adjustments & Concessions",
    moduleKey: "fees",
    category: "feature",
    description: "Apply fee discounts, scholarships, and custom fee adjustments.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees/adjust", method: "POST" }],
  },
  {
    id: "feature:fees.refund",
    key: "fees.refund",
    name: "Fee Refund Processing",
    moduleKey: "fees",
    category: "feature",
    description: "Issue fee refunds and ledger reversals.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees/refund", method: "POST" }],
  },
  {
    id: "feature:fees.export",
    key: "fees.export",
    name: "Export Fee Ledgers",
    moduleKey: "fees",
    category: "feature",
    description: "Export transaction ledgers and collection summaries.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees/export", method: "GET" }],
  },
  {
    id: "feature:fees.online_payment",
    key: "fees.online_payment",
    name: "Online Fee Payments Gateway",
    moduleKey: "fees",
    category: "feature",
    description: "Allow parents & students to pay school fees online via Razorpay/UPI.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/payments/create-order", method: "POST" }],
  },

  // Module: Homework
  {
    id: "feature:homework.view",
    key: "homework.view",
    name: "View Homework & Assignments",
    moduleKey: "homework",
    category: "feature",
    description: "Browse assigned tasks and past homework records.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/homework", method: "GET" }],
  },
  {
    id: "feature:homework.create",
    key: "homework.create",
    name: "Create & Assign Homework",
    moduleKey: "homework",
    category: "feature",
    description: "Publish new assignments with attachments and submission deadlines.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/homework", method: "POST" }],
  },
  {
    id: "feature:homework.review",
    key: "homework.review",
    name: "Evaluate & Grade Submissions",
    moduleKey: "homework",
    category: "feature",
    description: "Review student homework uploads and award marks/feedback.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/homework/review", method: "POST" }],
  },
  {
    id: "feature:homework.delete",
    key: "homework.delete",
    name: "Delete Homework Assignment",
    moduleKey: "homework",
    category: "feature",
    description: "Withdraw or delete an active assignment.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/homework", method: "DELETE" }],
  },

  // Module: Reports
  {
    id: "feature:reports.view",
    key: "reports.view",
    name: "View Platform Reports",
    moduleKey: "reports",
    category: "feature",
    description: "Access academic summaries, performance charts, and school metrics.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/reports", method: "GET" }],
  },
  {
    id: "feature:reports.generate",
    key: "reports.generate",
    name: "Generate Custom Reports",
    moduleKey: "reports",
    category: "feature",
    description: "Compile customized date-range and class performance reports.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/reports/generate", method: "POST" }],
  },
  {
    id: "feature:reports.export",
    key: "reports.export",
    name: "Export Platform Reports",
    moduleKey: "reports",
    category: "feature",
    description: "Download reports as PDF, Excel, and CSV documents.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/reports/export", method: "GET" }],
  },

  // Module: Exams
  {
    id: "feature:exams.view",
    key: "exams.view",
    name: "View Exam Schedules & Marks",
    moduleKey: "exams",
    category: "feature",
    description: "Inspect upcoming exams, test schedules, and mark distributions.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/exams", method: "GET" }],
  },
  {
    id: "feature:exams.create",
    key: "exams.create",
    name: "Create Exam Term",
    moduleKey: "exams",
    category: "feature",
    description: "Configure new examination terms, weightages, and grading rules.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/exams", method: "POST" }],
  },
  {
    id: "feature:exams.enter_marks",
    key: "exams.enter_marks",
    name: "Enter Student Marks",
    moduleKey: "exams",
    category: "feature",
    description: "Record scores and remarks for student exam papers.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/exams/marks", method: "POST" }],
  },
  {
    id: "feature:exams.publish",
    key: "exams.publish",
    name: "Publish Report Cards",
    moduleKey: "exams",
    category: "feature",
    description: "Release final term results and generate printable report cards.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/exams/publish", method: "POST" }],
  },

  // Module: Notices
  {
    id: "feature:notices.view",
    key: "notices.view",
    name: "View Notice Board",
    moduleKey: "notices",
    category: "feature",
    description: "Read school announcements and circulars.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/notices", method: "GET" }],
  },
  {
    id: "feature:notices.create",
    key: "notices.create",
    name: "Create Notice / Circular",
    moduleKey: "notices",
    category: "feature",
    description: "Draft and post new notices to students, parents, or staff.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/notices", method: "POST" }],
  },
  {
    id: "feature:notices.broadcast",
    key: "notices.broadcast",
    name: "Broadcast Emergency Notification",
    moduleKey: "notices",
    category: "feature",
    description: "Send high-priority instant notifications across all mobile portals.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/notices/broadcast", method: "POST" }],
  },

  // Module: Timetable
  {
    id: "feature:timetable.view",
    key: "timetable.view",
    name: "View Timetable",
    moduleKey: "timetable",
    category: "feature",
    description: "Check weekly schedules and class timetable grids.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/timetable", method: "GET" }],
  },
  {
    id: "feature:timetable.edit",
    key: "timetable.edit",
    name: "Edit & Publish Timetable",
    moduleKey: "timetable",
    category: "feature",
    description: "Modify period timings, subject allocations, and teacher schedules.",
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/timetable", method: "POST" }],
  },

  // =========================================================================
  // 3. ACTIONS & API KILL SWITCHES (DANGEROUS / HIGH IMPACT CONTROLS)
  // =========================================================================
  {
    id: "action:student.create",
    key: "action.student.create",
    name: "Kill Switch: Enroll Student",
    moduleKey: "students",
    category: "action",
    description: "Temporarily prevent creation of new student accounts across platforms.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students", method: "POST" }],
  },
  {
    id: "action:student.delete",
    key: "action.student.delete",
    name: "Kill Switch: Delete Student",
    moduleKey: "students",
    category: "action",
    description: "Emergency block on deleting or deactivating any student records.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students", method: "DELETE" }],
  },
  {
    id: "action:student.import",
    key: "action.student.import",
    name: "Kill Switch: Bulk CSV Import",
    moduleKey: "students",
    category: "action",
    description: "Block bulk batch imports to prevent accidental roster corruption.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/students/import", method: "POST" }],
  },
  {
    id: "action:fee.collect",
    key: "action.fee.collect",
    name: "Kill Switch: Collect Fee",
    moduleKey: "fees",
    category: "action",
    description: "Disables recording of offline fee payments and receipt issuance.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees/collect", method: "POST" }],
  },
  {
    id: "action:fee.refund",
    key: "action.fee.refund",
    name: "Kill Switch: Fee Refunds",
    moduleKey: "fees",
    category: "action",
    description: "Immediately disable all refund operations and ledger balance deductions.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/fees/refund", method: "POST" }],
  },
  {
    id: "action:payment.online",
    key: "action.payment.online",
    name: "Kill Switch: Online Payment Gateway",
    moduleKey: "fees",
    category: "action",
    description: "Halts all Razorpay checkout sessions and webhook order completions.",
    isDangerous: true,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [
      { path: "/api/payments/create-order", method: "POST" },
      { path: "/api/payments/verify", method: "POST" },
    ],
  },
  {
    id: "action:report.export",
    key: "action.report.export",
    name: "Kill Switch: Report Exports",
    moduleKey: "reports",
    category: "action",
    description: "Temporarily disable heavy export pipelines to protect server throughput.",
    isDangerous: false,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/admin/reports/export", method: "GET" }],
  },
  {
    id: "action:attendance.export",
    key: "action.attendance.export",
    name: "Kill Switch: Attendance Export",
    moduleKey: "attendance",
    category: "action",
    description: "Disable large register bulk downloads.",
    isDangerous: false,
    defaultRollout: "ON_FOR_ALL",
    apiEndpoints: [{ path: "/api/attendance/export", method: "GET" }],
  },
];

export function getFeatureDefinition(idOrKey: string): FeatureDefinition | undefined {
  return FEATURE_REGISTRY.find((f) => f.id === idOrKey || f.key === idOrKey);
}

export function getFeaturesByModule(moduleKey: string): FeatureDefinition[] {
  return FEATURE_REGISTRY.filter((f) => f.moduleKey === moduleKey);
}

export function getAllModules(): FeatureDefinition[] {
  return FEATURE_REGISTRY.filter((f) => f.category === "module");
}

export function getAllActions(): FeatureDefinition[] {
  return FEATURE_REGISTRY.filter((f) => f.category === "action");
}
