export interface NavigationShortcut {
  id: string;
  name: string;
  title: string;
  subtitle: string;
  keywords: string[];
  url: string;
  category: "navigation";
  type: "navigation";
}

export const SUPER_ADMIN_NAV_ITEMS: NavigationShortcut[] = [
  {
    id: "nav_schools",
    name: "Schools Directory",
    title: "Schools Directory",
    subtitle: "Manage all onboarded institutions & licenses",
    keywords: ["school", "schools", "institutions", "directory", "license", "colleges"],
    url: "/super-admin/schools",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_users",
    name: "Platform Users",
    title: "Platform Users",
    subtitle: "All school admins, teachers, and system accounts",
    keywords: ["users", "accounts", "admin", "teacher", "student", "roles", "staff"],
    url: "/super-admin/users",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_finance",
    name: "Finance Center",
    title: "Finance Center",
    subtitle: "Platform billing, plan subscriptions & revenue overview",
    keywords: ["finance", "billing", "revenue", "plans", "subscriptions", "payments", "invoices"],
    url: "/super-admin/finance",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_inquiries",
    name: "School Inquiries",
    title: "School Inquiries",
    subtitle: "Leads, demo inquiries & registration requests",
    keywords: ["inquiry", "inquiries", "leads", "contact", "demos", "crm"],
    url: "/super-admin/inquiries",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_communication",
    name: "Communication Hub",
    title: "Communication Hub",
    subtitle: "Global SMS, WhatsApp gateway, Twilio & dispatch logs",
    keywords: ["communication", "sms", "whatsapp", "twilio", "messaging", "broadcast"],
    url: "/super-admin/communication",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_analytics",
    name: "Platform Analytics",
    title: "Platform Analytics",
    subtitle: "Real-time ecosystem metrics & usage trends",
    keywords: ["analytics", "metrics", "reports", "stats", "growth", "dashboard"],
    url: "/super-admin/analytics",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_activity",
    name: "Security & Audit Logs",
    title: "Security & Audit Logs",
    subtitle: "Global login activity & platform audit trails",
    keywords: ["activity", "audit", "security", "logins", "compliance", "logs"],
    url: "/super-admin/activity/logins",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_offers",
    name: "Offers & Promotions",
    title: "Offers & Promotions",
    subtitle: "Coupon codes, discounts & promotional campaigns",
    keywords: ["offers", "promotions", "coupon", "discount", "campaign", "pricing"],
    url: "/super-admin/offers",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_showcase",
    name: "Feature Showcases",
    title: "Feature Showcases",
    subtitle: "Manage locked feature showcase previews",
    keywords: ["showcase", "features", "upsell", "banner"],
    url: "/super-admin/showcase",
    category: "navigation",
    type: "navigation",
  },
];

export const SCHOOL_ADMIN_NAV_ITEMS: NavigationShortcut[] = [
  {
    id: "nav_fees_collect",
    name: "Collect Fees",
    title: "Collect Fees",
    subtitle: "Student-wise fee collection & instant PDF receipt",
    keywords: ["fees", "collect", "payment", "cash", "deposit", "receipt", "fee", "paise"],
    url: "/admin/fees/collect",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_fees_invoice",
    name: "Generate Fees Invoice",
    title: "Generate Fees Invoice",
    subtitle: "Student, class & family 3-voucher bank challans",
    keywords: ["invoice", "challan", "bank", "fees", "generate", "bill", "demand"],
    url: "/admin/fees/generate-invoice",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_fees_slips",
    name: "Fees Paid Slips",
    title: "Fees Paid Slips",
    subtitle: "Locate, print & download official fee receipts",
    keywords: ["receipt", "slip", "paid", "reprint", "download", "pdf", "voucher"],
    url: "/admin/fees/paid-slip",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_fees_defaulters",
    name: "Fees Defaulters",
    title: "Fees Defaulters",
    subtitle: "Overdue fee dues & follow-up tracking",
    keywords: ["defaulter", "overdue", "pending", "unpaid", "reminder", "due"],
    url: "/admin/fees/defaulters",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_fees_structures",
    name: "Fee Structures",
    title: "Fee Structures",
    subtitle: "Define monthly, quarterly, annual fee heads",
    keywords: ["structure", "head", "tuition", "transport", "exam", "amount"],
    url: "/admin/fees/structures",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_fees_reports",
    name: "Fee Reports & Analytics",
    title: "Fee Reports & Analytics",
    subtitle: "Collections summary, balance sheet & export",
    keywords: ["reports", "collection", "summary", "analytics", "export", "excel"],
    url: "/admin/fees/reports",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_accounts_chart",
    name: "Chart of Accounts",
    title: "Chart of Accounts",
    subtitle: "Income and expense account heads & categories",
    keywords: ["accounts", "head", "chart", "ledger", "expense", "income", "voucher"],
    url: "/admin/accounts/chart-of-accounts",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_accounts_income",
    name: "Add Income",
    title: "Add Income",
    subtitle: "Record non-fee revenue, grants & sales",
    keywords: ["income", "revenue", "canteen", "donation", "grant", "received"],
    url: "/admin/accounts/add-income",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_accounts_expense",
    name: "Add Expense",
    title: "Add Expense",
    subtitle: "Record utility bills, fuel, repairs & supplies",
    keywords: ["expense", "bill", "fuel", "diesel", "stationery", "repair", "maintenance"],
    url: "/admin/accounts/add-expense",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_accounts_statement",
    name: "Account Statement",
    title: "Account Statement",
    subtitle: "General ledger, cash flow & financial PDF report",
    keywords: ["statement", "report", "pnl", "balance", "ledger", "audit", "transactions"],
    url: "/admin/accounts/statement",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_students_add",
    name: "Add Student (Admission)",
    title: "Add Student (Admission)",
    subtitle: "New student enrollment wizard",
    keywords: ["admission", "student", "enroll", "register", "new", "entry"],
    url: "/admin/students/add",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_students_all",
    name: "All Students Directory",
    title: "All Students Directory",
    subtitle: "Search, filter & manage student profiles",
    keywords: ["students", "directory", "nominal", "profiles", "list", "search"],
    url: "/admin/students",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_students_families",
    name: "Student Families",
    title: "Student Families",
    subtitle: "Group siblings by guardian / father & contact",
    keywords: ["family", "families", "guardian", "siblings", "parent", "father"],
    url: "/admin/students/families",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_students_id_cards",
    name: "Student ID Cards",
    title: "Student ID Cards",
    subtitle: "Batch identity card generator with QR code",
    keywords: ["id", "card", "badge", "identity", "print"],
    url: "/admin/students/id-cards",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_students_admission_letter",
    name: "Admission Letter",
    title: "Admission Letter",
    subtitle: "Formal joining letter & fee agreement",
    keywords: ["letter", "admission", "offer", "joining", "agreement"],
    url: "/admin/students/admission-letter",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_students_login",
    name: "Manage Student Login",
    title: "Manage Student Login",
    subtitle: "Portal credentials & WhatsApp pass dispatch",
    keywords: ["login", "password", "credentials", "whatsapp", "portal", "access"],
    url: "/admin/students/manage-login",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_students_promote",
    name: "Promote Students",
    title: "Promote Students",
    subtitle: "Academic batch roll-over & grade transfer",
    keywords: ["promote", "promotion", "transfer", "session", "batch", "upgrade"],
    url: "/admin/students/promote",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_teachers",
    name: "Teachers & Staff",
    title: "Teachers & Staff",
    subtitle: "Faculty profiles, subjects & contact info",
    keywords: ["teacher", "faculty", "staff", "employee", "salary", "teachers"],
    url: "/admin/teachers",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_attendance_students",
    name: "Student Attendance",
    title: "Student Attendance",
    subtitle: "Daily roll-call & absence tracking",
    keywords: ["attendance", "rollcall", "present", "absent", "student"],
    url: "/admin/attendance/students",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_attendance_employees",
    name: "Employee Attendance",
    title: "Employee Attendance",
    subtitle: "Staff roll-call & leave register",
    keywords: ["attendance", "staff", "employee", "leave", "absent"],
    url: "/admin/attendance/employees",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_timetable",
    name: "Timetable & Bells",
    title: "Timetable & Bells",
    subtitle: "Period schedules & class bells",
    keywords: ["timetable", "schedule", "bell", "period", "routine", "clock"],
    url: "/admin/timetable",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_classes",
    name: "Classes & Sections",
    title: "Classes & Sections",
    subtitle: "Classrooms, sections & student capacity",
    keywords: ["class", "section", "grade", "classroom", "classes"],
    url: "/admin/classes",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_billing",
    name: "Subscription & Plan",
    title: "Subscription & Plan",
    subtitle: "View current school ERP plan & limits",
    keywords: ["plan", "billing", "subscription", "upgrade", "pricing", "renew"],
    url: "/admin/billing",
    category: "navigation",
    type: "navigation",
  },
  {
    id: "nav_settings",
    name: "School Settings",
    title: "School Settings",
    subtitle: "School profile, logo, address & affiliation",
    keywords: ["settings", "school", "logo", "profile", "contact", "address"],
    url: "/admin/settings",
    category: "navigation",
    type: "navigation",
  },
];
